version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:latest
    ports:
      - "8081:5000"
    env_file:
      - ./server/.env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
     - "server"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    ports:
      - '8080:3000'
    depends_on:
      - "server"
