version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    ports:
      - '3000:3000'
    depends_on:
      - "server"
