version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server:latest
    ports:
      - "8080:5000"
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    ports:
      - '8081:3000'
    depends_on:
      - "server"
